name: cleanup caches by a branch

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4 # Utiliser la dernière version stable de l'action de checkout

      # Étape 2 : Suppression du cache
      - name: Cleanup cache
        run: |
          echo "PR Number is ${{ github.event.pull_request.number }}"
          echo "Fetching list of cache key"
          echo "Branch: $BRANCH"
          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')
          echo "Found cache keys: $cacheKeysForPR"

          if [ -z "$cacheKeysForPR" ]; then
            echo "No caches found for branch: $BRANCH"
          else
            ## Setting this to not fail the workflow while deleting cache keys.
            set +e
            echo "Deleting caches..."
            for cacheKey in $cacheKeysForPR
            do
                echo "Delete cache: $cacheKey"
                gh cache delete $cacheKey
            done
            echo "Done"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_CACHE }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/heads/${{ github.event.pull_request.head.ref }}
